import Head from "next/head";
import Navbar from "../components/NavbarSection/Navbar";
import Hero from "../components/HeroSection/Hero";
import CompanyInfo from "../components/CompanyInfoSection/CompanyInfo";
import Footer from "../components/FooterSection/Footer";
import styles from "../styles/Home.module.css";

export default function EEHome() {
    return (
        <div>
            <Head>
                <title>Easy Edit</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="logo.svg" />
            </Head>
            <Navbar />
            <Hero />
            <CompanyInfo />
            <Footer />
        </div>
    );
}